/**
 * Traductions complètes UI/Navigation pour les 24 langues européennes
 * Utilisé par les imports rapides du dashboard
 */

export const SECTIONS_TRANSLATIONS = {
  "section.1.title": {
    fr: "Profil Agence",
    en: "Agency Profile",
    de: "Agentenprofil",
    es: "Perfil de la Agencia",
    it: "Profilo Agenzia",
    nl: "Agentschapsprofiel",
    pl: "Profil Agencji",
    pt: "Perfil da Agência",
    cs: "Profil Agentury",
    sk: "Profil Agentúry",
    hu: "Ügynökség Profilja",
    ro: "Profil Agenție",
    bg: "Профил на Агенцията",
    hr: "Profil Agencije",
    sl: "Profil Agencije",
    et: "Agentuuri Profiil",
    lv: "Aģentūras Profils",
    lt: "Agentūros Profilis",
    el: "Προφίλ Οργανισμού",
    sv: "Byrå Profil",
    da: "Agentur Profil",
    fi: "Toimisto Profiili",
    no: "Byrå Profil"
  },
  "section.2.title": {
    fr: "Détachement",
    en: "Secondment",
    de: "Entsendung",
    es: "Desplazamiento",
    it: "Distacco",
    nl: "Detachering",
    pl: "Delegowanie",
    pt: "Destacamento",
    cs: "Vyslání",
    sk: "Vyslanie",
    hu: "Kiküldetés",
    ro: "Detașare",
    bg: "Командироване",
    hr: "Upućivanje",
    sl: "Napotitev",
    et: "Lähetamine",
    lv: "Komandējums",
    lt: "Komandiruotė",
    el: "Απόσπαση",
    sv: "Utstationering",
    da: "Udstationering",
    fi: "Lähettäminen",
    no: "Utstasjonering"
  },
  "section.3.title": {
    fr: "Besoins",
    en: "Needs",
    de: "Bedürfnisse",
    es: "Necesidades",
    it: "Esigenze",
    nl: "Behoeften",
    pl: "Potrzeby",
    pt: "Necessidades",
    cs: "Potřeby",
    sk: "Potreby",
    hu: "Szükségletek",
    ro: "Nevoi",
    bg: "Нужди",
    hr: "Potrebe",
    sl: "Potrebe",
    et: "Vajadused",
    lv: "Vajadzības",
    lt: "Poreikiai",
    el: "Ανάγκες",
    sv: "Behov",
    da: "Behov",
    fi: "Tarpeet",
    no: "Behov"
  },
  "section.4.title": {
    fr: "Intérêt YoJob",
    en: "YoJob Interest",
    de: "YoJob Interesse",
    es: "Interés YoJob",
    it: "Interesse YoJob",
    nl: "YoJob Interesse",
    pl: "Zainteresowanie YoJob",
    pt: "Interesse YoJob",
    cs: "Zájem YoJob",
    sk: "Záujem YoJob",
    hu: "YoJob Érdeklődés",
    ro: "Interes YoJob",
    bg: "Интерес към YoJob",
    hr: "Interes YoJob",
    sl: "Zanimanje YoJob",
    et: "YoJob Huvi",
    lv: "YoJob Interese",
    lt: "YoJob Susidomėjimas",
    el: "Ενδιαφέρον YoJob",
    sv: "YoJob Intresse",
    da: "YoJob Interesse",
    fi: "YoJob Kiinnostus",
    no: "YoJob Interesse"
  },
  "section.5.title": {
    fr: "Vision Future",
    en: "Future Vision",
    de: "Zukunftsvision",
    es: "Visión Futura",
    it: "Visione Futura",
    nl: "Toekomstvisie",
    pl: "Wizja Przyszłości",
    pt: "Visão Futura",
    cs: "Budoucí Vize",
    sk: "Budúca Vízia",
    hu: "Jövőkép",
    ro: "Viziune Viitoare",
    bg: "Бъдеща Визия",
    hr: "Buduća Vizija",
    sl: "Prihodnja Vizija",
    et: "Tuleviku Visioon",
    lv: "Nākotnes Vīzija",
    lt: "Ateities Vizija",
    el: "Μελλοντική Όραση",
    sv: "Framtidsvision",
    da: "Fremtidsvision",
    fi: "Tulevaisuuden Visio",
    no: "Fremtidsvisjon"
  },
  "section.6.title": {
    fr: "Contact",
    en: "Contact",
    de: "Kontakt",
    es: "Contacto",
    it: "Contatto",
    nl: "Contact",
    pl: "Kontakt",
    pt: "Contato",
    cs: "Kontakt",
    sk: "Kontakt",
    hu: "Kapcsolat",
    ro: "Contact",
    bg: "Контакт",
    hr: "Kontakt",
    sl: "Kontakt",
    et: "Kontakt",
    lv: "Kontakts",
    lt: "Kontaktas",
    el: "Επικοινωνία",
    sv: "Kontakt",
    da: "Kontakt",
    fi: "Yhteystiedot",
    no: "Kontakt"
  }
};

export const NAVIGATION_TRANSLATIONS = {
  "button.next": {
    fr: "Suivant",
    en: "Next",
    de: "Weiter",
    es: "Siguiente",
    it: "Avanti",
    nl: "Volgende",
    pl: "Dalej",
    pt: "Próximo",
    cs: "Další",
    sk: "Ďalej",
    hu: "Következő",
    ro: "Următorul",
    bg: "Следващ",
    hr: "Sljedeći",
    sl: "Naslednji",
    et: "Järgmine",
    lv: "Nākamais",
    lt: "Kitas",
    el: "Επόμενο",
    sv: "Nästa",
    da: "Næste",
    fi: "Seuraava",
    no: "Neste"
  },
  "button.previous": {
    fr: "Précédent",
    en: "Previous",
    de: "Zurück",
    es: "Anterior",
    it: "Precedente",
    nl: "Vorige",
    pl: "Poprzedni",
    pt: "Anterior",
    cs: "Předchozí",
    sk: "Predchádzajúci",
    hu: "Előző",
    ro: "Anterior",
    bg: "Предишен",
    hr: "Prethodni",
    sl: "Prejšnji",
    et: "Eelmine",
    lv: "Iepriekšējais",
    lt: "Ankstesnis",
    el: "Προηγούμενο",
    sv: "Föregående",
    da: "Forrige",
    fi: "Edellinen",
    no: "Forrige"
  },
  "button.submit": {
    fr: "Envoyer mes réponses",
    en: "Submit my answers",
    de: "Meine Antworten senden",
    es: "Enviar mis respuestas",
    it: "Invia le mie risposte",
    nl: "Mijn antwoorden verzenden",
    pl: "Wyślij moje odpowiedzi",
    pt: "Enviar minhas respostas",
    cs: "Odeslat odpovědi",
    sk: "Odoslať odpovede",
    hu: "Válaszok küldése",
    ro: "Trimite răspunsurile",
    bg: "Изпрати отговорите",
    hr: "Pošalji odgovore",
    sl: "Pošlji odgovore",
    et: "Saada vastused",
    lv: "Nosūtīt atbildes",
    lt: "Siųsti atsakymus",
    el: "Υποβολή απαντήσεων",
    sv: "Skicka svar",
    da: "Send svar",
    fi: "Lähetä vastaukset",
    no: "Send svar"
  },
  "button.submitting": {
    fr: "Envoi en cours...",
    en: "Sending...",
    de: "Wird gesendet...",
    es: "Enviando...",
    it: "Invio in corso...",
    nl: "Verzenden...",
    pl: "Wysyłanie...",
    pt: "Enviando...",
    cs: "Odesílání...",
    sk: "Odosielanie...",
    hu: "Küldés...",
    ro: "Se trimite...",
    bg: "Изпращане...",
    hr: "Slanje...",
    sl: "Pošiljanje...",
    et: "Saatmine...",
    lv: "Sūtīšana...",
    lt: "Siunčiama...",
    el: "Αποστολή...",
    sv: "Skickar...",
    da: "Sender...",
    fi: "Lähetetään...",
    no: "Sender..."
  },
  "helper.select_up_to_3": {
    fr: "Sélectionnez jusqu'à 3 secteurs",
    en: "Select up to 3 sectors",
    de: "Wählen Sie bis zu 3 Sektoren",
    es: "Seleccione hasta 3 sectores",
    it: "Seleziona fino a 3 settori",
    nl: "Selecteer maximaal 3 sectoren",
    pl: "Wybierz do 3 sektorów",
    pt: "Selecione até 3 setores",
    cs: "Vyberte až 3 sektory",
    sk: "Vyberte až 3 sektory",
    hu: "Válasszon legfeljebb 3 szektort",
    ro: "Selectați până la 3 sectoare",
    bg: "Изберете до 3 сектора",
    hr: "Odaberite do 3 sektora",
    sl: "Izberite do 3 sektorje",
    et: "Valige kuni 3 sektorit",
    lv: "Izvēlieties līdz 3 sektoriem",
    lt: "Pasirinkite iki 3 sektorių",
    el: "Επιλέξτε έως 3 τομείς",
    sv: "Välj upp till 3 sektorer",
    da: "Vælg op til 3 sektorer",
    fi: "Valitse enintään 3 sektoria",
    no: "Velg opptil 3 sektorer"
  },
  "nav.dashboard": {
    fr: "Dashboard",
    en: "Dashboard",
    de: "Dashboard",
    es: "Panel",
    it: "Dashboard",
    nl: "Dashboard",
    pl: "Panel",
    pt: "Painel",
    cs: "Přehled",
    sk: "Prehľad",
    hu: "Irányítópult",
    ro: "Panou",
    bg: "Табло",
    hr: "Nadzorna ploča",
    sl: "Nadzorna plošča",
    et: "Töölaud",
    lv: "Panelis",
    lt: "Skydelis",
    el: "Πίνακας ελέγχου",
    sv: "Instrumentpanel",
    da: "Dashboard",
    fi: "Hallintapaneeli",
    no: "Dashbord"
  },
  "nav.back_to_site": {
    fr: "Retour au site",
    en: "Back to site",
    de: "Zurück zur Website",
    es: "Volver al sitio",
    it: "Torna al sito",
    nl: "Terug naar site",
    pl: "Powrót do strony",
    pt: "Voltar ao site",
    cs: "Zpět na web",
    sk: "Späť na web",
    hu: "Vissza az oldalra",
    ro: "Înapoi la site",
    bg: "Назад към сайта",
    hr: "Povratak na stranicu",
    sl: "Nazaj na spletno mesto",
    et: "Tagasi saidile",
    lv: "Atpakaļ uz vietni",
    lt: "Grįžti į svetainę",
    el: "Επιστροφή στον ιστότοπο",
    sv: "Tillbaka till webbplatsen",
    da: "Tilbage til webstedet",
    fi: "Takaisin sivustolle",
    no: "Tilbake til nettstedet"
  }
};

/**
 * Convertit les traductions en format bulk import
 */
export function convertToSectionsFormat() {
  return Object.entries(SECTIONS_TRANSLATIONS).map(([key, translations]) => ({
    textId: key,
    key: key,
    category: "sections" as const,
    translations: Object.entries(translations).reduce((acc, [lang, text]) => ({
      ...acc,
      [lang]: { text, status: "validated" as const }
    }), {})
  }));
}

export function convertToNavigationFormat() {
  return Object.entries(NAVIGATION_TRANSLATIONS).map(([key, translations]) => {
    // Déterminer la catégorie automatiquement
    let category: "buttons" | "helpers" | "navigation";
    if (key.startsWith('button.')) {
      category = "buttons";
    } else if (key.startsWith('helper.')) {
      category = "helpers";
    } else {
      category = "navigation";
    }

    return {
      textId: key,
      key: key,
      category,
      translations: Object.entries(translations).reduce((acc, [lang, text]) => ({
        ...acc,
        [lang]: { text, status: "validated" as const }
      }), {})
    };
  });
}
