/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vhpbmckgxtdyxdwhmdxy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocGJtY2tneHRkeXhkd2htZHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNjE5ODUsImV4cCI6MjA3OTgzNzk4NX0.Vv0nIgRa91pi-trbK9drGTF6uoeCvvm4L2HEJ4UlyBo"

// Derived URL from projectId
export const supabaseUrl = `https://${projectId}.supabase.co`