import { motion } from 'motion/react';
import { CheckCircle, Circle, AlertCircle } from 'lucide-react';
import { Badge } from '../ui/badge';

interface LanguageProgress {
  code: string;
  name: string;
  flag: string;
  total: number;
  translated: number;
  validated: number;
  autoGenerated: number;
}

interface Props {
  languages: LanguageProgress[];
  onLanguageClick?: (code: string) => void;
}

export function LanguageProgressIndicator({ languages, onLanguageClick }: Props) {
  const getProgressColor = (percentage: number) => {
    if (percentage === 100) return 'from-green-500 to-emerald-500';
    if (percentage >= 75) return 'from-blue-500 to-cyan-500';
    if (percentage >= 50) return 'from-orange-500 to-amber-500';
    return 'from-red-500 to-rose-500';
  };

  const getProgressStatus = (percentage: number) => {
    if (percentage === 100) return 'Complété';
    if (percentage >= 75) return 'Avancé';
    if (percentage >= 50) return 'En cours';
    if (percentage > 0) return 'Démarré';
    return 'Non démarré';
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
      {languages.map((lang, idx) => {
        const percentage = lang.total > 0 ? (lang.translated / lang.total) * 100 : 0;
        const validatedPercentage = lang.total > 0 ? (lang.validated / lang.total) * 100 : 0;

        return (
          <motion.div
            key={lang.code}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.05 }}
            onClick={() => onLanguageClick?.(lang.code)}
            className={`bg-white border-2 border-slate-200 rounded-xl p-4 hover:border-violet-400 transition-all cursor-pointer group ${
              percentage === 100 ? 'ring-2 ring-green-200' : ''
            }`}
          >
            {/* Header */}
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <span className="text-2xl">{lang.flag}</span>
                <div>
                  <p className="text-slate-900">{lang.name}</p>
                  <p className="text-xs text-slate-500">{lang.code.toUpperCase()}</p>
                </div>
              </div>
              {percentage === 100 ? (
                <CheckCircle className="w-5 h-5 text-green-500" />
              ) : percentage > 0 ? (
                <Circle className="w-5 h-5 text-orange-400 fill-current" />
              ) : (
                <AlertCircle className="w-5 h-5 text-red-400" />
              )}
            </div>

            {/* Progress Bar */}
            <div className="mb-3">
              <div className="flex items-center justify-between text-xs text-slate-600 mb-1">
                <span>{getProgressStatus(percentage)}</span>
                <span className="font-mono">{percentage.toFixed(0)}%</span>
              </div>
              <div className="w-full bg-slate-100 rounded-full h-2.5 overflow-hidden">
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${percentage}%` }}
                  transition={{ duration: 0.8, delay: idx * 0.1 }}
                  className={`h-full bg-gradient-to-r ${getProgressColor(percentage)} relative`}
                >
                  {/* Validated portion (darker shade) */}
                  {validatedPercentage > 0 && (
                    <div
                      className="absolute inset-0 bg-gradient-to-r from-green-600 to-emerald-600"
                      style={{ width: `${(validatedPercentage / percentage) * 100}%` }}
                    />
                  )}
                </motion.div>
              </div>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-2">
              <div className="text-center">
                <p className="text-xs text-slate-500">Total</p>
                <p className="text-slate-900">{lang.translated}/{lang.total}</p>
              </div>
              <div className="text-center">
                <p className="text-xs text-slate-500">Validés</p>
                <p className="text-green-600">{lang.validated}</p>
              </div>
              <div className="text-center">
                <p className="text-xs text-slate-500">Auto</p>
                <p className="text-cyan-600">{lang.autoGenerated}</p>
              </div>
            </div>

            {/* Quality Badge */}
            {percentage === 100 && validatedPercentage === 100 && (
              <Badge className="w-full mt-3 bg-gradient-to-r from-green-500 to-emerald-500 text-white border-0">
                ✓ 100% Validé
              </Badge>
            )}
            {percentage === 100 && validatedPercentage < 100 && (
              <Badge variant="outline" className="w-full mt-3 border-orange-300 text-orange-700">
                ⚠️ À valider ({(100 - validatedPercentage).toFixed(0)}%)
              </Badge>
            )}
          </motion.div>
        );
      })}
    </div>
  );
}
