import { CompleteTranslationsSeeder } from './CompleteTranslationsSeeder';
import { TranslateClientWorkerProfiles } from './TranslateClientWorkerProfiles';
import { SeedAllFormsButton } from './SeedAllFormsButton';
import { SeedFromSurveyConfig } from './SeedFromSurveyConfig';
import { SeedWithProfilesButton } from './SeedWithProfilesButton';
import { useQuestions } from '../../context/QuestionsContext';
import { useTranslationContext } from '../../contexts/TranslationContext';
import { EUROPEAN_LANGUAGES } from '../../lib/languages';
import { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { 
  ArrowLeft, 
  Target, 
  CheckCircle, 
  Globe, 
  TrendingUp, 
  AlertTriangle, 
  Award 
} from 'lucide-react';

interface Props {
  onBack: () => void;
  onSelectLanguage?: (code: string) => void;
}

export function TranslationStatistics({ onBack, onSelectLanguage }: Props) {
  const { questions } = useQuestions();
  const { questionTranslations, uiTextTranslations, stats, loading } = useTranslationContext();
  const [languagesProgress, setLanguagesProgress] = useState<any[]>([]);

  // Calculate language progress from real data (questions + UI texts)
  useEffect(() => {
    if (!loading && questionTranslations && uiTextTranslations) {
      console.log('📊 [TranslationStatistics] Calculating stats:', {
        questionsCount: questionTranslations.length,
        uiTextsCount: uiTextTranslations.length,
        totalTexts: questionTranslations.length + uiTextTranslations.length,
      });
      
      const progress = EUROPEAN_LANGUAGES.map(lang => {
        let translated = 0;
        let validated = 0;
        let autoGenerated = 0;

        // Count QUESTIONS translations for this language
        questionTranslations.forEach(qt => {
          const translation = qt.translations[lang.code];
          if (translation && translation.text) {
            translated++;
            if (translation.status === 'validated') {
              validated++;
            } else if (translation.status === 'auto-mcp' || translation.status === 'auto-api') {
              autoGenerated++;
            }
          }
        });

        // Count UI TEXTS translations for this language
        uiTextTranslations.forEach(uit => {
          const translation = uit.translations[lang.code];
          if (translation && translation.text) {
            translated++;
            if (translation.status === 'validated') {
              validated++;
            } else if (translation.status === 'auto-mcp' || translation.status === 'auto-api') {
              autoGenerated++;
            }
          }
        });

        return {
          ...lang,
          total: questionTranslations.length + uiTextTranslations.length, // Total texts to translate
          translated,
          validated,
          autoGenerated,
        };
      });
      setLanguagesProgress(progress);
    }
  }, [loading, questionTranslations, uiTextTranslations]);

  // Calculate global statistics from real data (questions + UI texts)
  const totalTexts = questions.length + uiTextTranslations.length;
  const globalStats = {
    totalTranslations: totalTexts * (EUROPEAN_LANGUAGES.length - 1), // Total possible (sans FR source)
    completed: languagesProgress.reduce((acc, lang) => lang.code !== 'fr' ? acc + lang.translated : acc, 0),
    validated: languagesProgress.reduce((acc, lang) => lang.code !== 'fr' ? acc + lang.validated : acc, 0),
    autoGenerated: languagesProgress.reduce((acc, lang) => acc + lang.autoGenerated, 0),
  };

  const completionRate = globalStats.totalTranslations > 0
    ? (globalStats.completed / globalStats.totalTranslations) * 100
    : 0;
  const validationRate = globalStats.totalTranslations > 0
    ? (globalStats.validated / globalStats.totalTranslations) * 100
    : 0;
  const qualityRate = globalStats.completed > 0
    ? (globalStats.validated / globalStats.completed) * 100
    : 0;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <Button
            variant="ghost"
            onClick={onBack}
            className="mb-3 -ml-2 text-slate-600 hover:text-slate-900"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Retour
          </Button>
          <div>
            <h2 className="text-slate-900">📊 Statistiques de traduction</h2>
            <p className="text-slate-600 text-sm">
              Vue d'ensemble de la progression des traductions
            </p>
          </div>
        </div>
        
        {/* Diagnostic Badge */}
        <Badge 
          variant="outline" 
          className="bg-slate-100 border-slate-300 text-slate-700 px-3 py-1.5"
        >
          📦 {questionTranslations.length} questions + {uiTextTranslations.length} UI texts = {totalTexts} textes
        </Badge>
      </div>

      {/* Global Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="border-2 border-violet-200 bg-gradient-to-br from-violet-50 to-purple-50">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm text-slate-600 flex items-center gap-2">
              <Target className="w-4 h-4" />
              Progression globale
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-3xl text-violet-600 mb-1">{completionRate.toFixed(0)}%</p>
            <p className="text-sm text-slate-600">
              {globalStats.completed} / {globalStats.totalTranslations} traductions
            </p>
            <div className="w-full bg-violet-200 rounded-full h-2 overflow-hidden mt-2">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${completionRate}%` }}
                transition={{ duration: 1 }}
                className="h-full bg-gradient-to-r from-violet-500 to-purple-500"
              />
            </div>
          </CardContent>
        </Card>

        <Card className="border-2 border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm text-slate-600 flex items-center gap-2">
              <CheckCircle className="w-4 h-4" />
              Validées
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-3xl text-green-600 mb-1">{validationRate.toFixed(0)}%</p>
            <p className="text-sm text-slate-600">
              {globalStats.validated} traductions validées
            </p>
            <div className="w-full bg-green-200 rounded-full h-2 overflow-hidden mt-2">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${validationRate}%` }}
                transition={{ duration: 1, delay: 0.2 }}
                className="h-full bg-gradient-to-r from-green-500 to-emerald-500"
              />
            </div>
          </CardContent>
        </Card>

        <Card className="border-2 border-cyan-200 bg-gradient-to-br from-cyan-50 to-blue-50">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm text-slate-600 flex items-center gap-2">
              <Globe className="w-4 h-4" />
              Langues
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-3xl text-cyan-600 mb-1">{EUROPEAN_LANGUAGES.length}</p>
            <p className="text-sm text-slate-600">
              1 source + {EUROPEAN_LANGUAGES.length - 1} cibles
            </p>
            <div className="flex gap-1 mt-2 flex-wrap">
              {EUROPEAN_LANGUAGES.map(lang => (
                <span key={lang.code} className="text-lg" title={lang.name}>
                  {lang.flag}
                </span>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="border-2 border-orange-200 bg-gradient-to-br from-orange-50 to-amber-50">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm text-slate-600 flex items-center gap-2">
              <TrendingUp className="w-4 h-4" />
              Auto-générées
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-3xl text-orange-600 mb-1">{globalStats.autoGenerated}</p>
            <p className="text-sm text-slate-600">
              Traductions automatiques
            </p>
            <p className="text-xs text-orange-600 mt-2 flex items-center gap-1">
              <AlertTriangle className="w-3 h-3" />
              À valider manuellement
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Language Progress */}
      <Card className="border-slate-200">
        <CardHeader>
          <CardTitle className="text-slate-900">Progression par langue</CardTitle>
          <p className="text-sm text-slate-600">
            Cliquez sur une langue pour filtrer les traductions
          </p>
        </CardHeader>
        <CardContent>
          <LanguageProgressIndicator
            languages={languagesProgress}
            onLanguageClick={onSelectLanguage}
          />
        </CardContent>
      </Card>

      {/* Quality Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="border-slate-200">
          <CardContent className="p-6">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 flex items-center justify-center flex-shrink-0">
                <Award className="w-6 h-6 text-white" />
              </div>
              <div>
                <p className="text-sm text-slate-600 mb-1">Taux de qualité</p>
                <p className="text-2xl text-slate-900 mb-1">
                  {qualityRate.toFixed(0)}%
                </p>
                <p className="text-xs text-slate-500">
                  Traductions validées par des humains
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-slate-200">
          <CardContent className="p-6">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-500 to-blue-500 flex items-center justify-center flex-shrink-0">
                <Target className="w-6 h-6 text-white" />
              </div>
              <div>
                <p className="text-sm text-slate-600 mb-1">Textes complets</p>
                <p className="text-2xl text-slate-900 mb-1">
                  {languagesProgress.filter(lang => 
                    lang.code !== 'fr' && lang.translated === lang.total
                  ).length}/{totalTexts}
                </p>
                <p className="text-xs text-slate-500">
                  Traduits dans toutes les langues
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-slate-200">
          <CardContent className="p-6">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-violet-500 to-purple-500 flex items-center justify-center flex-shrink-0">
                <Globe className="w-6 h-6 text-white" />
              </div>
              <div>
                <p className="text-sm text-slate-600 mb-1">Couverture pays</p>
                <p className="text-2xl text-slate-900 mb-1">30</p>
                <p className="text-xs text-slate-500">
                  Pays européens couverts
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Missing Translations Diagnostic */}
      {completionRate < 100 && (
        <Card className="border-2 border-blue-200 bg-blue-50">
          <CardHeader>
            <CardTitle className="text-blue-900 flex items-center gap-2">
              <Target className="w-5 h-5" />
              📋 Diagnostic des traductions manquantes
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <p className="text-sm text-blue-800">
                <strong>Chaque langue devrait avoir {totalTexts} traductions</strong> ({questionTranslations.length} questions + {uiTextTranslations.length} UI texts)
              </p>
              
              {/* Breakdown by content type */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-3">
                <div className="bg-white/50 rounded-lg p-3 border border-blue-200">
                  <p className="text-xs text-blue-600 mb-1">📝 Questions du formulaire</p>
                  <p className="text-lg text-blue-900">{questionTranslations.length} questions</p>
                  <p className="text-xs text-blue-700 mt-1">
                    {languagesProgress.filter(l => l.code !== 'fr').reduce((acc, l) => {
                      return acc + questionTranslations.filter(q => q.translations[l.code]?.text).length;
                    }, 0)} / {questionTranslations.length * 22} traduites
                  </p>
                </div>
                
                <div className="bg-white/50 rounded-lg p-3 border border-blue-200">
                  <p className="text-xs text-blue-600 mb-1">🎨 Textes d'interface</p>
                  <p className="text-lg text-blue-900">{uiTextTranslations.length} textes UI</p>
                  <p className="text-xs text-blue-700 mt-1">
                    {languagesProgress.filter(l => l.code !== 'fr').reduce((acc, l) => {
                      return acc + uiTextTranslations.filter(u => u.translations[l.code]?.text).length;
                    }, 0)} / {uiTextTranslations.length * 22} traduites
                  </p>
                </div>
              </div>

              {/* What's missing per language */}
              <div className="bg-white/50 rounded-lg p-3 border border-blue-200 mt-3">
                <p className="text-xs text-blue-600 mb-2">🎯 Il manque en moyenne par langue :</p>
                <div className="flex items-center gap-4">
                  <div className="flex-1">
                    <div className="w-full bg-blue-200 rounded-full h-3 overflow-hidden">
                      <div 
                        className="h-full bg-gradient-to-r from-green-500 to-emerald-500"
                        style={{ width: `${completionRate}%` }}
                      />
                    </div>
                  </div>
                  <p className="text-2xl text-blue-900 font-mono">
                    {Math.round((1 - completionRate / 100) * totalTexts)} textes
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Complete Translations Seeder - THE ONLY SEEDER */}
      <CompleteTranslationsSeeder onComplete={() => {
        // Reload translations after seeding
        if (window.location.reload) {
          setTimeout(() => window.location.reload(), 1000);
        }
      }} />

      {/* NEW: Seed All Forms Translations (FR/EN/DE) */}
      <SeedAllFormsButton />

      {/* NEW: Translate Client & Worker Profiles Automatically */}
      <TranslateClientWorkerProfiles onComplete={() => {
        // Reload translations after completion
        if (window.location.reload) {
          setTimeout(() => window.location.reload(), 2000);
        }
      }} />

      {/* NEW: Seed From Survey Config */}
      <SeedFromSurveyConfig />

      {/* NEW: Seed With Profiles */}
      <SeedWithProfilesButton />

      {/* Recommendations */}
      <Card className="border-2 border-orange-200 bg-orange-50">
        <CardHeader>
          <CardTitle className="text-orange-900 flex items-center gap-2">
            <AlertTriangle className="w-5 h-5" />
            Recommandations
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          {completionRate < 50 && (
            <p className="text-sm text-orange-800">
              • Priorisez les traductions EN, DE et ES pour couvrir 70% du marché européen
            </p>
          )}
          {globalStats.autoGenerated > 10 && (
            <p className="text-sm text-orange-800">
              • {globalStats.autoGenerated} traductions automatiques nécessitent une validation manuelle
            </p>
          )}
          {validationRate < 80 && (
            <p className="text-sm text-orange-800">
              • Faites valider les traductions par des native speakers pour garantir la qualité
            </p>
          )}
          {completionRate >= 80 && (
            <p className="text-sm text-green-800">
              ✓ Excellent travail ! Vous êtes prêt à lancer les campagnes dans {Math.floor(completionRate / 12.5)} pays
            </p>
          )}
        </CardContent>
      </Card>
    </motion.div>
  );
}