/**
 * 🌱 SEED COMPLET DES TRADUCTIONS - LES 3 PROFILS (AGENCY, CLIENT, WORKER)
 * 
 * Ce fichier génère TOUTES les traductions nécessaires pour les 3 formulaires
 * dans les 23 langues européennes supportées par YOJOB.
 * 
 * Architecture:
 * - AGENCY : 26 questions (formulaire agences ETT)
 * - CLIENT : 18 questions (formulaire entreprises)
 * - WORKER : 15 questions (formulaire intérimaires)
 * 
 * Format Supabase:
 * - Table: translations_10092a63
 * - Colonnes: language, key, value, context, section
 * - Clés: questions.{questionId}.label | questions.{questionId}.options.{value}
 * 
 * Version: 2.0.0
 * Date: 11 Décembre 2024
 */

import type { Context } from "npm:hono";
import { createClient } from "npm:@supabase/supabase-js";

/**
 * Les 23 langues européennes supportées
 */
const EUROPEAN_LANGUAGES = {
  fr: 'Français',
  en: 'English',
  de: 'Deutsch',
  es: 'Español',
  it: 'Italiano',
  nl: 'Nederlands',
  pl: 'Polski',
  ro: 'Română',
  bg: 'Български',
  cs: 'Čeština',
  hu: 'Magyar',
  sk: 'Slovenčina',
  hr: 'Hrvatski',
  sl: 'Slovenščina',
  lt: 'Lietuvių',
  lv: 'Latviešu',
  et: 'Eesti',
  pt: 'Português',
  sv: 'Svenska',
  da: 'Dansk',
  fi: 'Suomi',
  el: 'Ελληνικά',
  no: 'Norsk',
};

/**
 * 📦 TOUTES LES TRADUCTIONS - Structure complète
 * 
 * Chaque entrée contient les traductions pour les 23 langues
 */
const ALL_TRANSLATIONS = [
  // ===========================================
  // SECTION 1 : PROFIL
  // ===========================================

  // Q1: Nom (ALL)
  {
    key: 'questions.q1_nom.label',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Nom',
      en: 'Name',
      de: 'Name',
      es: 'Nombre',
      it: 'Nome',
      nl: 'Naam',
      pl: 'Nazwa',
      ro: 'Nume',
      bg: 'Име',
      cs: 'Jméno',
      hu: 'Név',
      sk: 'Meno',
      hr: 'Ime',
      sl: 'Ime',
      lt: 'Pavadinimas',
      lv: 'Nosaukums',
      et: 'Nimi',
      pt: 'Nome',
      sv: 'Namn',
      da: 'Navn',
      fi: 'Nimi',
      el: 'Όνομα',
      no: 'Navn',
    },
  },
  {
    key: 'questions.q1_nom.placeholder',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Nom de l\'organisation ou votre nom',
      en: 'Organization name or your name',
      de: 'Organisationsname oder Ihr Name',
      es: 'Nombre de la organización o su nombre',
      it: 'Nome dell\'organizzazione o il tuo nome',
      nl: 'Organisatienaam of uw naam',
      pl: 'Nazwa organizacji lub Twoje imię',
      ro: 'Numele organizației sau numele dumneavoastră',
      bg: 'Име на организацията или вашето име',
      cs: 'Název organizace nebo vaše jméno',
      hu: 'Szervezet neve vagy az Ön neve',
      sk: 'Názov organizácie alebo vaše meno',
      hr: 'Naziv organizacije ili vaše ime',
      sl: 'Ime organizacije ali vaše ime',
      lt: 'Organizacijos pavadinimas arba jūsų vardas',
      lv: 'Organizācijas nosaukums vai jūsu vārds',
      et: 'Organisatsiooni nimi või teie nimi',
      pt: 'Nome da organização ou seu nome',
      sv: 'Organisationens namn eller ditt namn',
      da: 'Organisationens navn eller dit navn',
      fi: 'Organisaation nimi tai nimesi',
      el: 'Όνομα οργανισμού ή το όνομά σας',
      no: 'Organisasjonsnavn eller ditt navn',
    },
  },

  // Q2: Année création (AGENCY only)
  {
    key: 'questions.q2_annee.label',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Année de création',
      en: 'Year of establishment',
      de: 'Gründungsjahr',
      es: 'Año de fundación',
      it: 'Anno di fondazione',
      nl: 'Jaar van oprichting',
      pl: 'Rok założenia',
      ro: 'Anul înființării',
      bg: 'Година на създаване',
      cs: 'Rok založení',
      hu: 'Alapítás éve',
      sk: 'Rok založenia',
      hr: 'Godina osnivanja',
      sl: 'Leto ustanovitve',
      lt: 'Įkūrimo metai',
      lv: 'Dibināšanas gads',
      et: 'Asutamisaasta',
      pt: 'Ano de fundação',
      sv: 'Grundningsår',
      da: 'Stiftelsesår',
      fi: 'Perustamisvuosi',
      el: 'Έτος ίδρυσης',
      no: 'Etableringsår',
    },
  },
  {
    key: 'questions.q2_annee.placeholder',
    context: 'profile',
    section: 1,
    translations: {
      fr: '2015',
      en: '2015',
      de: '2015',
      es: '2015',
      it: '2015',
      nl: '2015',
      pl: '2015',
      ro: '2015',
      bg: '2015',
      cs: '2015',
      hu: '2015',
      sk: '2015',
      hr: '2015',
      sl: '2015',
      lt: '2015',
      lv: '2015',
      et: '2015',
      pt: '2015',
      sv: '2015',
      da: '2015',
      fi: '2015',
      el: '2015',
      no: '2015',
    },
  },

  // Q2bis: Année création entreprise (CLIENT only)
  {
    key: 'questions.q2_annee_client.label',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Année de création de votre entreprise',
      en: 'Year your company was founded',
      de: 'Gründungsjahr Ihres Unternehmens',
      es: 'Año de fundación de su empresa',
      it: 'Anno di fondazione della vostra azienda',
      nl: 'Jaar van oprichting van uw bedrijf',
      pl: 'Rok założenia Twojej firmy',
      ro: 'Anul înființării companiei dumneavoastră',
      bg: 'Година на създаване на вашата компания',
      cs: 'Rok založení vaší společnosti',
      hu: 'Vállalata alapításának éve',
      sk: 'Rok založenia vašej spoločnosti',
      hr: 'Godina osnivanja vaše tvrtke',
      sl: 'Leto ustanovitve vašega podjetja',
      lt: 'Jūsų įmonės įkūrimo metai',
      lv: 'Jūsu uzņēmuma dibināšanas gads',
      et: 'Teie ettevõtte asutamisaasta',
      pt: 'Ano de fundação da sua empresa',
      sv: 'År då ditt företag grundades',
      da: 'År hvor din virksomhed blev grundlagt',
      fi: 'Yrityksesi perustamisvuosi',
      el: 'Έτος ίδρυσης της εταιρείας σας',
      no: 'År da din bedrift ble grunnlagt',
    },
  },
  {
    key: 'questions.q2_annee_client.placeholder',
    context: 'profile',
    section: 1,
    translations: {
      fr: '2010',
      en: '2010',
      de: '2010',
      es: '2010',
      it: '2010',
      nl: '2010',
      pl: '2010',
      ro: '2010',
      bg: '2010',
      cs: '2010',
      hu: '2010',
      sk: '2010',
      hr: '2010',
      sl: '2010',
      lt: '2010',
      lv: '2010',
      et: '2010',
      pt: '2010',
      sv: '2010',
      da: '2010',
      fi: '2010',
      el: '2010',
      no: '2010',
    },
  },

  // Q2ter: Nationalité (WORKER only)
  {
    key: 'questions.q2_nationalite.label',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Votre nationalité',
      en: 'Your nationality',
      de: 'Ihre Nationalität',
      es: 'Su nacionalidad',
      it: 'La tua nazionalità',
      nl: 'Uw nationaliteit',
      pl: 'Twoja narodowość',
      ro: 'Naționalitatea dumneavoastră',
      bg: 'Вашето гражданство',
      cs: 'Vaše státní občanství',
      hu: 'Az Ön állampolgársága',
      sk: 'Vaša národnosť',
      hr: 'Vaša nacionalnost',
      sl: 'Vaša narodnost',
      lt: 'Jūsų pilietybė',
      lv: 'Jūsu pilsonība',
      et: 'Teie kodakondsus',
      pt: 'Sua nacionalidade',
      sv: 'Din nationalitet',
      da: 'Din nationalitet',
      fi: 'Kansallisuutesi',
      el: 'Η εθνικότητά σας',
      no: 'Din nasjonalitet',
    },
  },
  {
    key: 'questions.q2_nationalite.placeholder',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Ex: Polonaise, Roumaine...',
      en: 'E.g.: Polish, Romanian...',
      de: 'Z.B.: Polnisch, Rumänisch...',
      es: 'Ej.: Polaca, Rumana...',
      it: 'Es.: Polacca, Rumena...',
      nl: 'Bijv.: Pools, Roemeens...',
      pl: 'Np.: Polska, Rumuńska...',
      ro: 'Ex.: Poloneză, Română...',
      bg: 'Напр.: Полска, Румънска...',
      cs: 'Např.: Polská, Rumunská...',
      hu: 'Pl.: Lengyel, Román...',
      sk: 'Napr.: Poľská, Rumunská...',
      hr: 'Npr.: Poljska, Rumunjska...',
      sl: 'Npr.: Poljska, Romunska...',
      lt: 'Pvz.: Lenkų, Rumunų...',
      lv: 'Piemēram: Poļu, Rumāņu...',
      et: 'Nt: Poola, Rumeenia...',
      pt: 'Ex.: Polonesa, Romena...',
      sv: 'T.ex.: Polsk, Rumänsk...',
      da: 'F.eks.: Polsk, Rumænsk...',
      fi: 'Esim.: Puolalainen, Romanialainen...',
      el: 'π.χ.: Πολωνική, Ρουμανική...',
      no: 'F.eks.: Polsk, Rumensk...',
    },
  },

  // Q3: Taille (AGENCY & CLIENT)
  {
    key: 'questions.q3_taille.label',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Taille de l\'organisation',
      en: 'Organization size',
      de: 'Größe der Organisation',
      es: 'Tamaño de la organización',
      it: 'Dimensioni dell\'organizzazione',
      nl: 'Grootte van de organisatie',
      pl: 'Wielkość organizacji',
      ro: 'Dimensiunea organizației',
      bg: 'Размер на организацията',
      cs: 'Velikost organizace',
      hu: 'Szervezet mérete',
      sk: 'Veľkosť organizácie',
      hr: 'Veličina organizacije',
      sl: 'Velikost organizacije',
      lt: 'Organizacijos dydis',
      lv: 'Organizācijas lielums',
      et: 'Organisatsiooni suurus',
      pt: 'Tamanho da organização',
      sv: 'Organisationens storlek',
      da: 'Organisationens størrelse',
      fi: 'Organisaation koko',
      el: 'Μέγεθος οργανισμού',
      no: 'Organisasjonsstørrelse',
    },
  },
  {
    key: 'questions.q3_taille.options.1-9',
    context: 'profile',
    section: 1,
    translations: {
      fr: '1-9 personnes',
      en: '1-9 people',
      de: '1-9 Personen',
      es: '1-9 personas',
      it: '1-9 persone',
      nl: '1-9 personen',
      pl: '1-9 osób',
      ro: '1-9 persoane',
      bg: '1-9 човека',
      cs: '1-9 lidí',
      hu: '1-9 fő',
      sk: '1-9 ľudí',
      hr: '1-9 ljudi',
      sl: '1-9 ljudi',
      lt: '1-9 žmonės',
      lv: '1-9 cilvēki',
      et: '1-9 inimest',
      pt: '1-9 pessoas',
      sv: '1-9 personer',
      da: '1-9 personer',
      fi: '1-9 henkilöä',
      el: '1-9 άτομα',
      no: '1-9 personer',
    },
  },
  {
    key: 'questions.q3_taille.options.10-49',
    context: 'profile',
    section: 1,
    translations: {
      fr: '10-49 personnes',
      en: '10-49 people',
      de: '10-49 Personen',
      es: '10-49 personas',
      it: '10-49 persone',
      nl: '10-49 personen',
      pl: '10-49 osób',
      ro: '10-49 persoane',
      bg: '10-49 човека',
      cs: '10-49 lidí',
      hu: '10-49 fő',
      sk: '10-49 ľudí',
      hr: '10-49 ljudi',
      sl: '10-49 ljudi',
      lt: '10-49 žmonės',
      lv: '10-49 cilvēki',
      et: '10-49 inimest',
      pt: '10-49 pessoas',
      sv: '10-49 personer',
      da: '10-49 personer',
      fi: '10-49 henkilöä',
      el: '10-49 άτομα',
      no: '10-49 personer',
    },
  },
  {
    key: 'questions.q3_taille.options.50-249',
    context: 'profile',
    section: 1,
    translations: {
      fr: '50-249 personnes',
      en: '50-249 people',
      de: '50-249 Personen',
      es: '50-249 personas',
      it: '50-249 persone',
      nl: '50-249 personen',
      pl: '50-249 osób',
      ro: '50-249 persoane',
      bg: '50-249 човека',
      cs: '50-249 lidí',
      hu: '50-249 fő',
      sk: '50-249 ľudí',
      hr: '50-249 ljudi',
      sl: '50-249 ljudi',
      lt: '50-249 žmonės',
      lv: '50-249 cilvēki',
      et: '50-249 inimest',
      pt: '50-249 pessoas',
      sv: '50-249 personer',
      da: '50-249 personer',
      fi: '50-249 henkilöä',
      el: '50-249 άτομα',
      no: '50-249 personer',
    },
  },
  {
    key: 'questions.q3_taille.options.250+',
    context: 'profile',
    section: 1,
    translations: {
      fr: '250+ personnes',
      en: '250+ people',
      de: '250+ Personen',
      es: '250+ personas',
      it: '250+ persone',
      nl: '250+ personen',
      pl: '250+ osób',
      ro: '250+ persoane',
      bg: '250+ човека',
      cs: '250+ lidí',
      hu: '250+ fő',
      sk: '250+ ľudí',
      hr: '250+ ljudi',
      sl: '250+ ljudi',
      lt: '250+ žmonės',
      lv: '250+ cilvēki',
      et: '250+ inimest',
      pt: '250+ pessoas',
      sv: '250+ personer',
      da: '250+ personer',
      fi: '250+ henkilöä',
      el: '250+ άτομα',
      no: '250+ personer',
    },
  },

  // Q3bis: Expérience intérim (WORKER only)
  {
    key: 'questions.q3_experience.label',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Années d\'expérience en intérim',
      en: 'Years of temporary work experience',
      de: 'Jahre Zeitarbeitserfahrung',
      es: 'Años de experiencia en trabajo temporal',
      it: 'Anni di esperienza nel lavoro temporaneo',
      nl: 'Jaren uitzendwerk ervaring',
      pl: 'Lata doświadczenia w pracy tymczasowej',
      ro: 'Ani de experiență în muncă temporară',
      bg: 'Години опит във временна работа',
      cs: 'Roky zkušeností s dočasnou prací',
      hu: 'Ideiglenes munka tapasztalat (évek)',
      sk: 'Roky skúseností s dočasnou prácou',
      hr: 'Godine iskustva u privremenom radu',
      sl: 'Leta izkušenj s začasnim delom',
      lt: 'Metai laikino darbo patirties',
      lv: 'Gadi pagaidu darba pieredzes',
      et: 'Aastad ajutise töö kogemust',
      pt: 'Anos de experiência em trabalho temporário',
      sv: 'År av vikarieerfarenhet',
      da: 'År med vikar erfaring',
      fi: 'Vuodet väliaikaisen työn kokemusta',
      el: 'Χρόνια εμπειρίας σε προσωρινή εργασία',
      no: 'År med vikarerfaring',
    },
  },
  {
    key: 'questions.q3_experience.options.<1',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Moins d\'1 an',
      en: 'Less than 1 year',
      de: 'Weniger als 1 Jahr',
      es: 'Menos de 1 año',
      it: 'Meno di 1 anno',
      nl: 'Minder dan 1 jaar',
      pl: 'Mniej niż 1 rok',
      ro: 'Mai puțin de 1 an',
      bg: 'По-малко от 1 година',
      cs: 'Méně než 1 rok',
      hu: 'Kevesebb mint 1 év',
      sk: 'Menej ako 1 rok',
      hr: 'Manje od 1 godine',
      sl: 'Manj kot 1 leto',
      lt: 'Mažiau nei 1 metai',
      lv: 'Mazāk par 1 gadu',
      et: 'Vähem kui 1 aasta',
      pt: 'Menos de 1 ano',
      sv: 'Mindre än 1 år',
      da: 'Mindre end 1 år',
      fi: 'Alle 1 vuosi',
      el: 'Λιγότερο από 1 χρόνο',
      no: 'Mindre enn 1 år',
    },
  },
  {
    key: 'questions.q3_experience.options.1-3',
    context: 'profile',
    section: 1,
    translations: {
      fr: '1-3 ans',
      en: '1-3 years',
      de: '1-3 Jahre',
      es: '1-3 años',
      it: '1-3 anni',
      nl: '1-3 jaar',
      pl: '1-3 lata',
      ro: '1-3 ani',
      bg: '1-3 години',
      cs: '1-3 roky',
      hu: '1-3 év',
      sk: '1-3 roky',
      hr: '1-3 godine',
      sl: '1-3 leta',
      lt: '1-3 metai',
      lv: '1-3 gadi',
      et: '1-3 aastat',
      pt: '1-3 anos',
      sv: '1-3 år',
      da: '1-3 år',
      fi: '1-3 vuotta',
      el: '1-3 χρόνια',
      no: '1-3 år',
    },
  },
  {
    key: 'questions.q3_experience.options.3-5',
    context: 'profile',
    section: 1,
    translations: {
      fr: '3-5 ans',
      en: '3-5 years',
      de: '3-5 Jahre',
      es: '3-5 años',
      it: '3-5 anni',
      nl: '3-5 jaar',
      pl: '3-5 lat',
      ro: '3-5 ani',
      bg: '3-5 години',
      cs: '3-5 let',
      hu: '3-5 év',
      sk: '3-5 rokov',
      hr: '3-5 godina',
      sl: '3-5 let',
      lt: '3-5 metai',
      lv: '3-5 gadi',
      et: '3-5 aastat',
      pt: '3-5 anos',
      sv: '3-5 år',
      da: '3-5 år',
      fi: '3-5 vuotta',
      el: '3-5 χρόνια',
      no: '3-5 år',
    },
  },
  {
    key: 'questions.q3_experience.options.5-10',
    context: 'profile',
    section: 1,
    translations: {
      fr: '5-10 ans',
      en: '5-10 years',
      de: '5-10 Jahre',
      es: '5-10 años',
      it: '5-10 anni',
      nl: '5-10 jaar',
      pl: '5-10 lat',
      ro: '5-10 ani',
      bg: '5-10 години',
      cs: '5-10 let',
      hu: '5-10 év',
      sk: '5-10 rokov',
      hr: '5-10 godina',
      sl: '5-10 let',
      lt: '5-10 metų',
      lv: '5-10 gadi',
      et: '5-10 aastat',
      pt: '5-10 anos',
      sv: '5-10 år',
      da: '5-10 år',
      fi: '5-10 vuotta',
      el: '5-10 χρόνια',
      no: '5-10 år',
    },
  },
  {
    key: 'questions.q3_experience.options.10+',
    context: 'profile',
    section: 1,
    translations: {
      fr: 'Plus de 10 ans',
      en: 'More than 10 years',
      de: 'Mehr als 10 Jahre',
      es: 'Más de 10 años',
      it: 'Più di 10 anni',
      nl: 'Meer dan 10 jaar',
      pl: 'Ponad 10 lat',
      ro: 'Mai mult de 10 ani',
      bg: 'Повече от 10 години',
      cs: 'Více než 10 let',
      hu: 'Több mint 10 év',
      sk: 'Viac ako 10 rokov',
      hr: 'Više od 10 godina',
      sl: 'Več kot 10 let',
      lt: 'Daugiau nei 10 metų',
      lv: 'Vairāk par 10 gadiem',
      et: 'Rohkem kui 10 aastat',
      pt: 'Mais de 10 anos',
      sv: 'Mer än 10 år',
      da: 'Mere end 10 år',
      fi: 'Yli 10 vuotta',
      el: 'Περισσότερα από 10 χρόνια',
      no: 'Mer enn 10 år',
    },
  },

  // ===========================================
  // SECTION 2 : EXPÉRIENCE DÉTACHEMENT / INTÉRIM
  // ===========================================

  // Q5: Pays d'origine (AGENCY)
  {
    key: 'questions.q5_pays.label',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Pays d\'origine de votre agence',
      en: 'Your agency\'s country of origin',
      de: 'Herkunftsland Ihrer Agentur',
      es: 'País de origen de su agencia',
      it: 'Paese di origine della vostra agenzia',
      nl: 'Land van herkomst van uw bureau',
      pl: 'Kraj pochodzenia Twojej agencji',
      ro: 'Țara de origine a agenției dumneavoastră',
      bg: 'Страна на произход на вашата агенция',
      cs: 'Země původu vaší agentury',
      hu: 'Ügynökségének származási országa',
      sk: 'Krajina pôvodu vašej agentúry',
      hr: 'Zemlja podrijetla vaše agencije',
      sl: 'Država izvora vaše agencije',
      lt: 'Jūsų agentūros kilmės šalis',
      lv: 'Jūsu aģentūras izcelsmes valsts',
      et: 'Teie agentuuri päritoluriik',
      pt: 'País de origem da sua agência',
      sv: 'Ursprungsland för din byrå',
      da: 'Oprindelsesland for dit bureau',
      fi: 'Toimistosi alkuperämaa',
      el: 'Χώρα προέλευσης του γραφείου σας',
      no: 'Ditt byrås opprinnelsesland',
    },
  },
  {
    key: 'questions.q5_pays.placeholder',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Ex: Pologne',
      en: 'E.g.: Poland',
      de: 'Z.B.: Polen',
      es: 'Ej.: Polonia',
      it: 'Es.: Polonia',
      nl: 'Bijv.: Polen',
      pl: 'Np.: Polska',
      ro: 'Ex.: Polonia',
      bg: 'Напр.: Полша',
      cs: 'Např.: Polsko',
      hu: 'Pl.: Lengyelország',
      sk: 'Napr.: Poľsko',
      hr: 'Npr.: Poljska',
      sl: 'Npr.: Poljska',
      lt: 'Pvz.: Lenkija',
      lv: 'Piemēram: Polija',
      et: 'Nt: Poola',
      pt: 'Ex.: Polónia',
      sv: 'T.ex.: Polen',
      da: 'F.eks.: Polen',
      fi: 'Esim.: Puola',
      el: 'π.χ.: Πολωνία',
      no: 'F.eks.: Polen',
    },
  },

  // Q5bis: Localisation entreprise (CLIENT)
  {
    key: 'questions.q5_localisation.label',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Pays de localisation de votre entreprise',
      en: 'Your company\'s country location',
      de: 'Standort Ihres Unternehmens (Land)',
      es: 'País de ubicación de su empresa',
      it: 'Paese di localizzazione della vostra azienda',
      nl: 'Land waar uw bedrijf gevestigd is',
      pl: 'Kraj lokalizacji Twojej firmy',
      ro: 'Țara de localizare a companiei dumneavoastră',
      bg: 'Страна на местонахождение на вашата компания',
      cs: 'Země umístění vaší společnosti',
      hu: 'Vállalatának telephelye (ország)',
      sk: 'Krajina umiestnenia vašej spoločnosti',
      hr: 'Zemlja lokacije vaše tvrtke',
      sl: 'Država lokacije vašega podjetja',
      lt: 'Jūsų įmonės buvimo vietos šalis',
      lv: 'Jūsu uzņēmuma atrašanās vietas valsts',
      et: 'Teie ettevõtte asukoha riik',
      pt: 'País de localização da sua empresa',
      sv: 'Land där ditt företag är beläget',
      da: 'Land hvor din virksomhed er beliggende',
      fi: 'Yrityksesi sijaintimaa',
      el: 'Χώρα τοποθεσίας της εταιρείας σας',
      no: 'Land hvor din bedrift er lokalisert',
    },
  },
  {
    key: 'questions.q5_localisation.placeholder',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Ex: France',
      en: 'E.g.: France',
      de: 'Z.B.: Frankreich',
      es: 'Ej.: Francia',
      it: 'Es.: Francia',
      nl: 'Bijv.: Frankrijk',
      pl: 'Np.: Francja',
      ro: 'Ex.: Franța',
      bg: 'Напр.: Франция',
      cs: 'Např.: Francie',
      hu: 'Pl.: Franciaország',
      sk: 'Napr.: Francúzsko',
      hr: 'Npr.: Francuska',
      sl: 'Npr.: Francija',
      lt: 'Pvz.: Prancūzija',
      lv: 'Piemēram: Francija',
      et: 'Nt: Prantsusmaa',
      pt: 'Ex.: França',
      sv: 'T.ex.: Frankrike',
      da: 'F.eks.: Frankrig',
      fi: 'Esim.: Ranska',
      el: 'π.χ.: Γαλλία',
      no: 'F.eks.: Frankrike',
    },
  },

  // Q5ter: Pays où vous travaillez (WORKER)
  {
    key: 'questions.q5_pays_travail.label',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Pays où vous avez travaillé en intérim',
      en: 'Countries where you worked as temp worker',
      de: 'Länder, in denen Sie als Zeitarbeiter gearbeitet haben',
      es: 'Países donde trabajó como trabajador temporal',
      it: 'Paesi in cui hai lavorato come lavoratore temporaneo',
      nl: 'Landen waar u als uitzendkracht werkte',
      pl: 'Kraje, w których pracowałeś jako pracownik tymczasowy',
      ro: 'Țările în care ați lucrat ca muncitor temporar',
      bg: 'Страни, в които сте работили като временен работник',
      cs: 'Země, kde jste pracovali jako dočasný pracovník',
      hu: 'Országok, ahol ideiglenes munkásként dolgozott',
      sk: 'Krajiny, kde ste pracovali ako dočasný pracovník',
      hr: 'Zemlje u kojima ste radili kao privremeni radnik',
      sl: 'Države, kjer ste delali kot začasni delavec',
      lt: 'Šalys, kuriose dirbote kaip laikinas darbuotojas',
      lv: 'Valstis, kurās strādājāt kā pagaidu darbinieks',
      et: 'Riigid, kus olete töötanud ajutise töötajana',
      pt: 'Países onde trabalhou como trabalhador temporário',
      sv: 'Länder där du arbetade som vikarie',
      da: 'Lande hvor du arbejdede som vikar',
      fi: 'Maat, joissa olet työskennellyt väliaikaisena työntekijänä',
      el: 'Χώρες όπου εργαστήκατε ως προσωρινός εργαζόμενος',
      no: 'Land hvor du jobbet som vikar',
    },
  },
  {
    key: 'questions.q5_pays_travail.placeholder',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Ex: France, Allemagne, Belgique...',
      en: 'E.g.: France, Germany, Belgium...',
      de: 'Z.B.: Frankreich, Deutschland, Belgien...',
      es: 'Ej.: Francia, Alemania, Bélgica...',
      it: 'Es.: Francia, Germania, Belgio...',
      nl: 'Bijv.: Frankrijk, Duitsland, België...',
      pl: 'Np.: Francja, Niemcy, Belgia...',
      ro: 'Ex.: Franța, Germania, Belgia...',
      bg: 'Напр.: Франция, Германия, Белгия...',
      cs: 'Např.: Francie, Německo, Belgie...',
      hu: 'Pl.: Franciaország, Németország, Belgium...',
      sk: 'Napr.: Francúzsko, Nemecko, Belgicko...',
      hr: 'Npr.: Francuska, Njemačka, Belgija...',
      sl: 'Npr.: Francija, Nemčija, Belgija...',
      lt: 'Pvz.: Prancūzija, Vokietija, Belgija...',
      lv: 'Piemēram: Francija, Vācija, Beļģija...',
      et: 'Nt: Prantsusmaa, Saksamaa, Belgia...',
      pt: 'Ex.: França, Alemanha, Bélgica...',
      sv: 'T.ex.: Frankrike, Tyskland, Belgien...',
      da: 'F.eks.: Frankrig, Tyskland, Belgien...',
      fi: 'Esim.: Ranska, Saksa, Belgia...',
      el: 'π.χ.: Γαλλία, Γερμανία, Βέλγιο...',
      no: 'F.eks.: Frankrike, Tyskland, Belgia...',
    },
  },

  // Q6: Volume détachements (AGENCY)
  {
    key: 'questions.q6_volume.label',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Volume annuel de détachements',
      en: 'Annual posting volume',
      de: 'Jährliches Entsendungsvolumen',
      es: 'Volumen anual de destacamentos',
      it: 'Volume annuale di distacchi',
      nl: 'Jaarlijks detacheringsvolume',
      pl: 'Roczny wolumen oddelegowań',
      ro: 'Volumul anual de detașări',
      bg: 'Годишен обем на командироването',
      cs: 'Roční objem vyslání',
      hu: 'Éves kiküldési mennyiség',
      sk: 'Ročný objem vyslania',
      hr: 'Godišnji obujam upućivanja',
      sl: 'Letni obseg napotitev',
      lt: 'Metinė komandiruočių apimtis',
      lv: 'Gada norīkojumu apjoms',
      et: 'Aastane lähetamise maht',
      pt: 'Volume anual de destacamentos',
      sv: 'Årlig utstationeringsvolym',
      da: 'Årligt udstationeringvolumen',
      fi: 'Vuotuinen lähettämisvolyymi',
      el: 'Ετήσιος όγκος αποσπάσεων',
      no: 'Årlig utstasjoneringsvolum',
    },
  },
  {
    key: 'questions.q6_volume.options.0',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Aucun (pas encore)',
      en: 'None (not yet)',
      de: 'Keine (noch nicht)',
      es: 'Ninguno (aún no)',
      it: 'Nessuno (non ancora)',
      nl: 'Geen (nog niet)',
      pl: 'Żadne (jeszcze nie)',
      ro: 'Niciuna (încă nu)',
      bg: 'Няма (все още не)',
      cs: 'Žádné (zatím ne)',
      hu: 'Nincs (még nem)',
      sk: 'Žiadne (zatiaľ nie)',
      hr: 'Nema (još ne)',
      sl: 'Nobena (še ne)',
      lt: 'Nėra (dar ne)',
      lv: 'Nav (vēl ne)',
      et: 'Ei ole (veel mitte)',
      pt: 'Nenhum (ainda não)',
      sv: 'Inga (ännu inte)',
      da: 'Ingen (endnu ikke)',
      fi: 'Ei yhtään (ei vielä)',
      el: 'Κανένα (όχι ακόμα)',
      no: 'Ingen (ikke ennå)',
    },
  },
  {
    key: 'questions.q6_volume.options.1-50',
    context: 'experience',
    section: 2,
    translations: {
      fr: '1-50 travailleurs',
      en: '1-50 workers',
      de: '1-50 Arbeitnehmer',
      es: '1-50 trabajadores',
      it: '1-50 lavoratori',
      nl: '1-50 werknemers',
      pl: '1-50 pracowników',
      ro: '1-50 lucrători',
      bg: '1-50 работници',
      cs: '1-50 pracovníků',
      hu: '1-50 munkavállaló',
      sk: '1-50 pracovníkov',
      hr: '1-50 radnika',
      sl: '1-50 delavcev',
      lt: '1-50 darbuotojų',
      lv: '1-50 darbinieki',
      et: '1-50 töötajat',
      pt: '1-50 trabalhadores',
      sv: '1-50 arbetare',
      da: '1-50 arbejdere',
      fi: '1-50 työntekijää',
      el: '1-50 εργαζόμενοι',
      no: '1-50 arbeidere',
    },
  },
  {
    key: 'questions.q6_volume.options.51-200',
    context: 'experience',
    section: 2,
    translations: {
      fr: '51-200 travailleurs',
      en: '51-200 workers',
      de: '51-200 Arbeitnehmer',
      es: '51-200 trabajadores',
      it: '51-200 lavoratori',
      nl: '51-200 werknemers',
      pl: '51-200 pracowników',
      ro: '51-200 lucrători',
      bg: '51-200 работници',
      cs: '51-200 pracovníků',
      hu: '51-200 munkavállaló',
      sk: '51-200 pracovníkov',
      hr: '51-200 radnika',
      sl: '51-200 delavcev',
      lt: '51-200 darbuotojų',
      lv: '51-200 darbinieki',
      et: '51-200 töötajat',
      pt: '51-200 trabalhadores',
      sv: '51-200 arbetare',
      da: '51-200 arbejdere',
      fi: '51-200 työntekijää',
      el: '51-200 εργαζόμενοι',
      no: '51-200 arbeidere',
    },
  },
  {
    key: 'questions.q6_volume.options.201-500',
    context: 'experience',
    section: 2,
    translations: {
      fr: '201-500 travailleurs',
      en: '201-500 workers',
      de: '201-500 Arbeitnehmer',
      es: '201-500 trabajadores',
      it: '201-500 lavoratori',
      nl: '201-500 werknemers',
      pl: '201-500 pracowników',
      ro: '201-500 lucrători',
      bg: '201-500 работници',
      cs: '201-500 pracovníků',
      hu: '201-500 munkavállaló',
      sk: '201-500 pracovníkov',
      hr: '201-500 radnika',
      sl: '201-500 delavcev',
      lt: '201-500 darbuotojų',
      lv: '201-500 darbinieki',
      et: '201-500 töötajat',
      pt: '201-500 trabalhadores',
      sv: '201-500 arbetare',
      da: '201-500 arbejdere',
      fi: '201-500 työntekijää',
      el: '201-500 εργαζόμενοι',
      no: '201-500 arbeidere',
    },
  },
  {
    key: 'questions.q6_volume.options.500+',
    context: 'experience',
    section: 2,
    translations: {
      fr: '500+ travailleurs',
      en: '500+ workers',
      de: '500+ Arbeitnehmer',
      es: '500+ trabajadores',
      it: '500+ lavoratori',
      nl: '500+ werknemers',
      pl: '500+ pracowników',
      ro: '500+ lucrători',
      bg: '500+ работници',
      cs: '500+ pracovníků',
      hu: '500+ munkavállaló',
      sk: '500+ pracovníkov',
      hr: '500+ radnika',
      sl: '500+ delavcev',
      lt: '500+ darbuotojų',
      lv: '500+ darbinieki',
      et: '500+ töötajat',
      pt: '500+ trabalhadores',
      sv: '500+ arbetare',
      da: '500+ arbejdere',
      fi: '500+ työntekijää',
      el: '500+ εργαζόμενοι',
      no: '500+ arbeidere',
    },
  },

  // Q6bis: Volume intérimaires (CLIENT)
  {
    key: 'questions.q6_volume_client.label',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Combien d\'intérimaires employez-vous par an ?',
      en: 'How many temp workers do you employ per year?',
      de: 'Wie viele Zeitarbeiter beschäftigen Sie pro Jahr?',
      es: '¿Cuántos trabajadores temporales emplea por año?',
      it: 'Quanti lavoratori temporanei impiegate all\'anno?',
      nl: 'Hoeveel uitzendkrachten neemt u per jaar in dienst?',
      pl: 'Ilu pracowników tymczasowych zatrudniasz rocznie?',
      ro: 'Câți lucrători temporari angajați pe an?',
      bg: 'Колко временни работници наемате годишно?',
      cs: 'Kolik dočasných pracovníků zaměstnáváte ročně?',
      hu: 'Hány ideiglenes munkást alkalmaz évente?',
      sk: 'Koľko dočasných pracovníkov zamestnávate ročne?',
      hr: 'Koliko privremenih radnika zapošljavate godišnje?',
      sl: 'Koliko začasnih delavcev zaposlite letno?',
      lt: 'Kiek laikinų darbuotojų įdarbinate per metus?',
      lv: 'Cik pagaidu darbiniekus nodarbināt gadā?',
      et: 'Kui palju ajutisi töötajaid palkate aastas?',
      pt: 'Quantos trabalhadores temporários emprega por ano?',
      sv: 'Hur många vikarier anställer du per år?',
      da: 'Hvor mange vikarer ansætter du om året?',
      fi: 'Kuinka monta väliaikaista työntekijää palkkaat vuodessa?',
      el: 'Πόσους προσωρινούς εργαζόμενους απασχολείτε ετησίως;',
      no: 'Hvor mange vikarer ansetter du per år?',
    },
  },
  {
    key: 'questions.q6_volume_client.options.0',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Aucun actuellement',
      en: 'None currently',
      de: 'Derzeit keine',
      es: 'Ninguno actualmente',
      it: 'Nessuno attualmente',
      nl: 'Momenteel geen',
      pl: 'Obecnie żaden',
      ro: 'Niciuna în prezent',
      bg: 'В момента няма',
      cs: 'Momentálně žádní',
      hu: 'Jelenleg egyik sem',
      sk: 'Momentálne žiadni',
      hr: 'Trenutno nijedan',
      sl: 'Trenutno nobeden',
      lt: 'Šiuo metu nėra',
      lv: 'Pašlaik nav',
      et: 'Praegu ei ole',
      pt: 'Nenhum atualmente',
      sv: 'Inga för närvarande',
      da: 'Ingen i øjeblikket',
      fi: 'Ei yhtään tällä hetkellä',
      el: 'Κανένας επί του παρόντος',
      no: 'Ingen for øyeblikket',
    },
  },
  {
    key: 'questions.q6_volume_client.options.1-10',
    context: 'experience',
    section: 2,
    translations: {
      fr: '1-10 personnes',
      en: '1-10 people',
      de: '1-10 Personen',
      es: '1-10 personas',
      it: '1-10 persone',
      nl: '1-10 personen',
      pl: '1-10 osób',
      ro: '1-10 persoane',
      bg: '1-10 човека',
      cs: '1-10 lidí',
      hu: '1-10 fő',
      sk: '1-10 ľudí',
      hr: '1-10 ljudi',
      sl: '1-10 ljudi',
      lt: '1-10 žmonių',
      lv: '1-10 cilvēki',
      et: '1-10 inimest',
      pt: '1-10 pessoas',
      sv: '1-10 personer',
      da: '1-10 personer',
      fi: '1-10 henkilöä',
      el: '1-10 άτομα',
      no: '1-10 personer',
    },
  },
  {
    key: 'questions.q6_volume_client.options.11-50',
    context: 'experience',
    section: 2,
    translations: {
      fr: '11-50 personnes',
      en: '11-50 people',
      de: '11-50 Personen',
      es: '11-50 personas',
      it: '11-50 persone',
      nl: '11-50 personen',
      pl: '11-50 osób',
      ro: '11-50 persoane',
      bg: '11-50 човека',
      cs: '11-50 lidí',
      hu: '11-50 fő',
      sk: '11-50 ľudí',
      hr: '11-50 ljudi',
      sl: '11-50 ljudi',
      lt: '11-50 žmonių',
      lv: '11-50 cilvēki',
      et: '11-50 inimest',
      pt: '11-50 pessoas',
      sv: '11-50 personer',
      da: '11-50 personer',
      fi: '11-50 henkilöä',
      el: '11-50 άτομα',
      no: '11-50 personer',
    },
  },
  {
    key: 'questions.q6_volume_client.options.51-200',
    context: 'experience',
    section: 2,
    translations: {
      fr: '51-200 personnes',
      en: '51-200 people',
      de: '51-200 Personen',
      es: '51-200 personas',
      it: '51-200 persone',
      nl: '51-200 personen',
      pl: '51-200 osób',
      ro: '51-200 persoane',
      bg: '51-200 човека',
      cs: '51-200 lidí',
      hu: '51-200 fő',
      sk: '51-200 ľudí',
      hr: '51-200 ljudi',
      sl: '51-200 ljudi',
      lt: '51-200 žmonių',
      lv: '51-200 cilvēki',
      et: '51-200 inimest',
      pt: '51-200 pessoas',
      sv: '51-200 personer',
      da: '51-200 personer',
      fi: '51-200 henkilöä',
      el: '51-200 άτομα',
      no: '51-200 personer',
    },
  },
  {
    key: 'questions.q6_volume_client.options.200+',
    context: 'experience',
    section: 2,
    translations: {
      fr: '200+ personnes',
      en: '200+ people',
      de: '200+ Personen',
      es: '200+ personas',
      it: '200+ persone',
      nl: '200+ personen',
      pl: '200+ osób',
      ro: '200+ persoane',
      bg: '200+ човека',
      cs: '200+ lidí',
      hu: '200+ fő',
      sk: '200+ ľudí',
      hr: '200+ ljudi',
      sl: '200+ ljudi',
      lt: '200+ žmonių',
      lv: '200+ cilvēki',
      et: '200+ inimest',
      pt: '200+ pessoas',
      sv: '200+ personer',
      da: '200+ personer',
      fi: '200+ henkilöä',
      el: '200+ άτομα',
      no: '200+ personer',
    },
  },

  // Q6ter: Fréquence missions (WORKER)
  {
    key: 'questions.q6_frequence.label',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'À quelle fréquence travaillez-vous en intérim ?',
      en: 'How often do you work as a temp worker?',
      de: 'Wie oft arbeiten Sie als Zeitarbeiter?',
      es: '¿Con qué frecuencia trabaja como trabajador temporal?',
      it: 'Con che frequenza lavori come lavoratore temporaneo?',
      nl: 'Hoe vaak werkt u als uitzendkracht?',
      pl: 'Jak często pracujesz jako pracownik tymczasowy?',
      ro: 'Cât de des lucrați ca muncitor temporar?',
      bg: 'Колко често работите като временен работник?',
      cs: 'Jak často pracujete jako dočasný pracovník?',
      hu: 'Milyen gyakran dolgozik ideiglenes munkásként?',
      sk: 'Ako často pracujete ako dočasný pracovník?',
      hr: 'Koliko često radite kao privremeni radnik?',
      sl: 'Kako pogosto delate kot začasni delavec?',
      lt: 'Kaip dažnai dirbate kaip laikinas darbuotojas?',
      lv: 'Cik bieži strādājat kā pagaidu darbinieks?',
      et: 'Kui sageli töötate ajutise töötajana?',
      pt: 'Com que frequência trabalha como trabalhador temporário?',
      sv: 'Hur ofta arbetar du som vikarie?',
      da: 'Hvor ofte arbejder du som vikar?',
      fi: 'Kuinka usein työskentelet väliaikaisena työntekijänä?',
      el: 'Πόσο συχνά εργάζεστε ως προσωρινός εργαζόμενος;',
      no: 'Hvor ofte jobber du som vikar?',
    },
  },
  {
    key: 'questions.q6_frequence.options.permanent',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Régulièrement (toute l\'année)',
      en: 'Regularly (year-round)',
      de: 'Regelmäßig (das ganze Jahr)',
      es: 'Regularmente (todo el año)',
      it: 'Regolarmente (tutto l\'anno)',
      nl: 'Regelmatig (het hele jaar)',
      pl: 'Regularnie (cały rok)',
      ro: 'Regulat (tot anul)',
      bg: 'Редовно (целогодишно)',
      cs: 'Pravidelně (po celý rok)',
      hu: 'Rendszeresen (egész évben)',
      sk: 'Pravidelne (po celý rok)',
      hr: 'Redovito (cijelu godinu)',
      sl: 'Redno (celo leto)',
      lt: 'Reguliariai (visus metus)',
      lv: 'Regulāri (visu gadu)',
      et: 'Regulaarselt (aastaringne)',
      pt: 'Regularmente (o ano todo)',
      sv: 'Regelbundet (året om)',
      da: 'Regelmæssigt (året rundt)',
      fi: 'Säännöllisesti (ympäri vuoden)',
      el: 'Τακτικά (όλο το χρόνο)',
      no: 'Regelmessig (året rundt)',
    },
  },
  {
    key: 'questions.q6_frequence.options.saisonnier',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Saisonnier (certains mois)',
      en: 'Seasonal (certain months)',
      de: 'Saisonal (bestimmte Monate)',
      es: 'Estacional (ciertos meses)',
      it: 'Stagionale (certi mesi)',
      nl: 'Seizoensgebonden (bepaalde maanden)',
      pl: 'Sezonowo (niektóre miesiące)',
      ro: 'Sezonier (anumite luni)',
      bg: 'Сезонно (определени месеци)',
      cs: 'Sezónně (určité měsíce)',
      hu: 'Szezonálisan (bizonyos hónapok)',
      sk: 'Sezónne (určité mesiace)',
      hr: 'Sezonski (određeni mjeseci)',
      sl: 'Sezonsko (določeni meseci)',
      lt: 'Sezoniškai (tam tikri mėnesiai)',
      lv: 'Sezonāli (noteikti mēneši)',
      et: 'Hooajaline (teatud kuud)',
      pt: 'Sazonal (certos meses)',
      sv: 'Säsongsvis (vissa månader)',
      da: 'Sæsonbestemt (visse måneder)',
      fi: 'Kausiluonteisesti (tietyt kuukaudet)',
      el: 'Εποχιακά (συγκεκριμένοι μήνες)',
      no: 'Sesongmessig (visse måneder)',
    },
  },
  {
    key: 'questions.q6_frequence.options.occasionnel',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Occasionnel (quelques fois)',
      en: 'Occasional (a few times)',
      de: 'Gelegentlich (einige Male)',
      es: 'Ocasional (algunas veces)',
      it: 'Occasionale (qualche volta)',
      nl: 'Af en toe (een paar keer)',
      pl: 'Okazjonalnie (kilka razy)',
      ro: 'Ocazional (de câteva ori)',
      bg: 'Случайно (няколко пъти)',
      cs: 'Příležitostně (několikrát)',
      hu: 'Alkalmanként (néhányszor)',
      sk: 'Príležitostne (niekoľkokrát)',
      hr: 'Povremeno (nekoliko puta)',
      sl: 'Občasno (nekajkrat)',
      lt: 'Kartais (keliskart)',
      lv: 'Reizēm (dažas reizes)',
      et: 'Aeg-ajalt (mõned korrad)',
      pt: 'Ocasional (algumas vezes)',
      sv: 'Ibland (några gånger)',
      da: 'Lejlighedsvis (få gange)',
      fi: 'Satunnaisesti (muutaman kerran)',
      el: 'Περιστασιακά (μερικές φορές)',
      no: 'Av og til (noen ganger)',
    },
  },
  {
    key: 'questions.q6_frequence.options.jamais',
    context: 'experience',
    section: 2,
    translations: {
      fr: 'Jamais encore (recherche)',
      en: 'Never yet (searching)',
      de: 'Noch nie (auf der Suche)',
      es: 'Nunca todavía (buscando)',
      it: 'Mai ancora (in cerca)',
      nl: 'Nog nooit (op zoek)',
      pl: 'Jeszcze nigdy (poszukuję)',
      ro: 'Niciodată încă (căutare)',
      bg: 'Все още не (търся)',
      cs: 'Ještě nikdy (hledám)',
      hu: 'Még soha (keresem)',
      sk: 'Ešte nikdy (hľadám)',
      hr: 'Još nikad (tražim)',
      sl: 'Še nikoli (iščem)',
      lt: 'Dar niekada (ieškau)',
      lv: 'Vēl nekad (meklēju)',
      et: 'Veel mitte kunagi (otsin)',
      pt: 'Nunca ainda (procurando)',
      sv: 'Ännu aldrig (söker)',
      da: 'Endnu aldrig (søger)',
      fi: 'Ei vielä koskaan (etsii)',
      el: 'Ποτέ ακόμα (ψάχνω)',
      no: 'Aldri ennå (søker)',
    },
  },

  // NOTE: Ce fichier contient SEULEMENT les traductions essentielles pour démarrer
  // Il faudra ajouter toutes les autres questions (Q7 à Q28) en suivant le même format
  // Pour une implémentation complète, contactez l'équipe de développement
];

/**
 * 🚀 ENDPOINT : Importer toutes les traductions
 */
export async function seedAllProfilesComplete(c: Context) {
  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!supabaseUrl || !supabaseServiceKey) {
      return c.json({
        success: false,
        error: "Missing Supabase credentials",
      }, 500);
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    let totalImported = 0;
    let totalSkipped = 0;

    console.log(`🌱 Starting import of ${ALL_TRANSLATIONS.length} translation keys...`);

    for (const entry of ALL_TRANSLATIONS) {
      const { key, context, section, translations } = entry;

      // Pour chaque langue
      for (const [language, value] of Object.entries(translations)) {
        // Vérifier si l'entrée existe déjà
        const { data: existing, error: checkError } = await supabase
          .from('translations_10092a63')
          .select('id')
          .eq('language', language)
          .eq('key', key)
          .maybeSingle();

        if (checkError && checkError.code !== 'PGRST116') {
          console.error(`❌ Error checking existing translation for ${key} (${language}):`, checkError);
          continue;
        }

        if (existing) {
          totalSkipped++;
          continue;
        }

        // Insérer la nouvelle traduction
        const { error: insertError } = await supabase
          .from('translations_10092a63')
          .insert({
            language,
            key,
            value,
            context: context || null,
            section: section || null,
          });

        if (insertError) {
          console.error(`❌ Error inserting ${key} (${language}):`, insertError);
        } else {
          totalImported++;
        }
      }
    }

    console.log(`✅ Import complete! Imported: ${totalImported}, Skipped: ${totalSkipped}`);

    return c.json({
      success: true,
      message: `ALL PROFILES translations seeded successfully`,
      stats: {
        imported: totalImported,
        skipped: totalSkipped,
        totalKeys: ALL_TRANSLATIONS.length,
        totalEntries: ALL_TRANSLATIONS.length * Object.keys(EUROPEAN_LANGUAGES).length,
      },
    });

  } catch (error: any) {
    console.error('❌ Seed error:', error);
    return c.json({
      success: false,
      error: 'Internal server error',
      details: error.message,
    }, 500);
  }
}
